version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=achatdb
    ports:
        - 3306:3306
    networks:
        - springmysql-net
  app_chat:
    image : ahmedazizelj/achat_back
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
       - 8089:8089
    environment:
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://localhost:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.show-sql"= "true",
            "spring.jpa.hibernate.ddl-auto"= "update",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
          }'
    networks:
      - springmysql-net

networks:
  springmysql-net: